// Canned "AI" drafts per (opportunity, section). Stand-ins for the real Claude
// two-pass output; they intentionally re-use phrases from the artist's kit
// (statements, project descriptions, work captions) so the diff renderer can
// visualize voice preservation.

export const mockDrafts: Record<string, Record<string, string>> = {
  opp_macdowell: {
    project_description:
      "At MacDowell I would continue Outbuildings, a two-year project gathering material from five closed Rust Belt sites and restitching it into a single room-scale installation. The residency would cover the early studio phase: testing how three new bodies of material — conveyor belting from the Aliquippa Works, fabric from Cannon Mills, and rolling-mill remnants from Sloss Furnaces — combine in one piece.\n\nThe work is hand-stitched and riveted. Pieces range from 4 to 9 feet vertical, hung from forged steel hooks. I will bring my Singer 132K6 industrial machine and a portable propane forge (with permission for outdoor use). The studio needs 12 ft ceilings, no plinth, and floor protection — the mill scale sheds. I would bring approximately 60 cubic feet of material in two crates.\n\nI have already completed the Aliquippa fieldwork with Rivers of Steel; MacDowell would be the first sustained period to test the three sites' materials together before fabrication of the touring installation begins."
  },
  opp_creative_capital: {
    one_line:
      "Outbuildings is a two-year project gathering material from five closed Rust Belt sites — Aliquippa, Cannon Mills, Sloss Furnaces, Acme Steel, American Brass — and restitching it into a touring room-scale installation, a sound piece built from on-site conversations, and an open material archive.",
    project_description:
      "Outbuildings extends nine years of fieldwork inside closed industrial sites into a single two-year project with three outputs: a touring room-scale installation, a sound piece, and an open material archive.\n\nThe fieldwork covers five sites: the Aliquippa Works (PA, closed 1985), Cannon Mills (NC, closed 2003), Sloss Furnaces (AL), the Acme Steel works (Chicago), and the former American Brass campus (CT). Three heritage organizations are committed; the remaining two are in conversation. At each site I gather rolling-mill remnants, conveyor belting, and textile scraps under a formal provenance protocol I developed at the 2024 Aliquippa pilot.\n\nThe studio component restitches and rivets these materials into a single room-scale installation that travels to three venues: the Mattress Factory, the Cleveland Museum of Art, and SculptureCenter (all in early conversation). The installation reconfigures for each space; floor and walls are part of the work.\n\nA parallel sound piece is built from on-site conversations recorded with site stewards — short, edited into a spatialized score that plays in the installation, evidence sitting alongside the material.\n\nThe third component is an open material archive, hosted by Rivers of Steel, documenting every material's provenance, fabrication history, gathering protocol, and the conversation it came with. It outlives any one exhibition.\n\nWhy now: three of the five sites are in active demolition or sale conversations. The material window is closing. Stewards have asked for the work to happen now.\n\nWhy me: nine years building this practice; the Aliquippa pilot established the protocol; the heritage organizations involved have asked for it to expand.",
    impact_audience:
      "Outbuildings reaches three audiences: the heritage communities at each site, contemporary-art audiences at three institutional venues, and a long-tail of researchers and artists via the open archive. Site visits include public conversations co-hosted with the heritage organizations — small, on-site, recorded with consent — that the stewards have asked for as part of the protocol. The archive is the durable layer: a public catalogue, mirrored at the venues and at Rivers of Steel, that other artists, historians, and the heritage organizations themselves can use after the exhibition closes.",
    values_alignment:
      "The bold new vision is the archive: a public, structured record of how this kind of work can be made — provenance, protocol, conversation — that turns a single artist's practice into a resource for the field. The urgency is concrete: three of five sites are in demolition or sale conversations. The material window is closing."
  },
  opp_nyfa: {
    work_statement:
      "Sculptures and room-scale installations from material gathered inside closed steel mills and textile plants across the Rust Belt. Conveyor belting, mill rags, rolling-mill remnants — restitched into figures that sit between mourning and refusal. The landscape didn't die, it was unmade, and the materials still have a position on the matter.",
    work_sample_info:
      "Five works tracing a single methodology across three sites — Aliquippa, Cannon Mills, the Carrie Furnace. Each was produced after a sanctioned site visit with the heritage organization stewarding the building, with formal provenance documentation. Studio process is hand-stitched and riveted; the work is hung from forged steel hooks rather than plinthed. Image 1 (Aliquippa Carrier) uses a 12-foot section of conveyor belting that moved coke through the Aliquippa rolling mill from 1958 until plant closure in 1985. Image 2 (Half-Life Garments) gathers fabric scraps from the Cannon Mills site into eleven garment-like hangings. Image 3 (Forum 91) was a floor work for Carnegie Museum of Art's group exhibition. Image 4 (After the Furnace) is a suite of five wall-mounted forms made during a residency at Bemis. Image 5 (Field Recording) is a slow-pan video made during a sanctioned walk-through of the Carrie Furnace site."
  },
  opp_fca_emergency: {
    project_narrative:
      "I have a confirmed installation at Pioneer Works on July 14, 2026 (eight weeks out). The piece — a new floor work made from conveyor belting recovered at the Aliquippa Works — needs a freight transit insurance rider that wasn't in the original Pioneer Works budget. The work weighs 340 lbs and has $14,000 in declared value (the heritage agreement requires it). The transit is from my Brooklyn studio to Red Hook, four miles. The insurance rider is $1,850. Without it the venue cannot accept delivery and the install date will not hold. This is a one-night opening tied to a scheduled public conversation with Ron Baraff of Rivers of Steel, who is flying in for the event. The conversation cannot reschedule.",
    budget_narrative:
      "Single line: transit insurance rider for the work's declared value during the four-mile move from studio to Pioneer Works.\n· Transit insurance rider · 1 × $1,850 · $1,850\nNo other lines. Pioneer Works covers freight; the artist covers the rider per the heritage-agreement provenance contract.",
    venue_confirmation:
      "Venue: Pioneer Works, 159 Pioneer St, Brooklyn, NY 11231. Date: July 14, 2026, opening 7–10pm, with on-stage conversation 8–9pm. Curator contact: Tomashi Jackson (Director of Visual Arts Programs). Public-facing event page is live. Ron Baraff (Rivers of Steel) confirmed travel."
  },
  opp_rijksakademie: {
    motivation:
      "I want the two years at Rijksakademie now because Outbuildings is at the moment in its arc where the studio testing matters more than the fieldwork. I have spent nine years building a practice around salvaged industrial material across the American Rust Belt; the next phase needs the long horizon and the technical workshops that Rijksakademie offers — particularly the metal and textile shops, and the long-format conversation with a cohort of artists I do not already know.\n\nI am drawn to Rijksakademie's structure of two years without the obligation to produce a final show. My work moves slowly. The Aliquippa Carrier pieces took eighteen months from gathering to install; the Half-Life Garments installation took fourteen. A two-year window without the deliverable pressure would let me work through three Rust Belt sites' materials in parallel and see how they speak to each other under a single roof, with technical staff to consult on conservation and assembly questions I currently solve by guessing.\n\nThe community engagement piece matters to me. The conversations I have in the studio in Brooklyn are with people who already know the work. At Rijksakademie I would be inside a cohort working in registers I have not had access to — sound, performance, architecture — and that pressure is what I am looking for. I expect my work to be re-shaped by it, and that is the point of going. I would propose to host a working group on materials with provenance: artists across disciplines who are building practices around objects that came from somewhere specific. The format I have in mind is a monthly closed-door studio rotation."
  }
};

export function getMockDraft(oppId: string, sectionKey: string): string {
  return mockDrafts[oppId]?.[sectionKey] ?? "Claude drafts the section here, recombining phrases from your kit (statements, project descriptions, work captions) and tailoring them to this funder's prompt, length, and stated values.";
}
